title:                 Action is character manifested
description:           Taking inquisitive and augmenting it with python to learn about the world.

url:                   https://AgustinCody.com
baseurl:               ""

remote_theme:          hydecorp/hydejack@v9

accent_image:          /img/path.jpg
accent_color:          rgb(79,177,186)
theme_color:           rgb(25,55,71)

google_fonts:          false

author:
  name:                Agustin Vargas
  tagline:             Action is character manifested — exploring data, life, and everything in between.
  email:               AgustinVargas@ProtonMail.com
  picture:             /img/profile-pic.png

social:
  name:                Agustin Vargas
  links:
    - https://twitter.com/sentientcells
    - https://www.linkedin.com/in/vargasstem/
    - https://github.com/AVData


menu:
  - title: Blog
    url:   /
  - title: Archive
    url:   /archive/
  - title: About
    url:   /aboutme/

hydejack:
  dark_mode:
    always:            true
  post_addons:         [about, related]
  project_addons:      [about, other]
  no_mark_external:    false
  no_push_state:       false
  no_drawer:           false
  no_navbar:           false
  no_search:           false
  no_inline_css:       false
  no_page_style:       false
  no_break_layout:     true
  no_toc:              false
  no_third_column:     false
  no_large_headings:   false
  no_structured_data:  false
  no_theme_color:      false
  no_breadcrumbs:      false
  use_lsi:             true

timezone:              America/Los_Angeles
markdown:              kramdown
highlighter:           rouge
permalink:             /:year-:month-:day-:title/
paginate:              5

kramdown:
  input:               GFM

defaults:
  - scope:
      path:            ""
      type:            posts
    values:
      layout:          post
      comments:        false
  - scope:
      path:            ""
    values:
      layout:          page

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

exclude:
  - CHANGELOG.md
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
